version: "3.8"

services:
  postgres:
    container_name: "tubee_db"
    env_file:
      - ".env"
    image: "postgres:12-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  celery:
    command:
      [
        "watchmedo",
        "auto-restart",
        "--directory=./",
        "--pattern=*.py",
        "--recursive",
        "--",
        "celery",
        "--app=celery_worker.celery",
        "worker",
        "--loglevel=info",
      ]
    container_name: "tubee_celery"
    depends_on:
      - "rabbitmq"
    env_file:
      - ".env"
    environment:
      FLASK_ENV: "development"
    image: "tomy0000000/tubee"
    network_mode: "host"
    volumes:
      - ".:/usr/src/tubee"
  rabbitmq:
    container_name: "tubee_rabbitmq"
    hostname: "tubee-rabbitmq"
    image: "rabbitmq:3.8"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"

volumes:
  rabbitmq_data:
  postgres_data:
