"""empty message

Revision ID: 87c9d0a2bcc2
Revises: d853ab6aaf68
Create Date: 2019-04-11 16:45:26.841518

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87c9d0a2bcc2'
down_revision = 'd853ab6aaf68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('callback', sa.Column('action', sa.String(length=30), nullable=False))
    op.add_column('callback', sa.Column('arguments', sa.JSON(), nullable=False))
    op.add_column('callback', sa.Column('data', sa.Text(), nullable=False))
    op.add_column('callback', sa.Column('user_agent', sa.String(length=200), nullable=False))
    # op.drop_column('callback', 'action_type')
    # ### end Alembic commands ###
    op.alter_column('callback', 'action_type', new_column_name='action', existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('callback', sa.Column('action_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=False))
    op.drop_column('callback', 'user_agent')
    op.drop_column('callback', 'data')
    op.drop_column('callback', 'arguments')
    # op.drop_column('callback', 'action')
    # ### end Alembic commands ###
    op.alter_column('callback', 'action', new_column_name='action_type', existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30))
