"""empty message

Revision ID: d853ab6aaf68
Revises: 3b7a313a1cb3
Create Date: 2019-04-10 16:43:56.473650

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd853ab6aaf68'
down_revision = '3b7a313a1cb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('subscription', sa.Column('custom_url', sa.String(length=100), nullable=True))
    # op.drop_column('subscription', 'customUrl')
    # ### end Alembic commands ###
    op.alter_column('subscription', 'customUrl', new_column_name='custom_url', existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('subscription', sa.Column('customUrl', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), server_default=sa.text("'NULL'"), nullable=True))
    # op.drop_column('subscription', 'custom_url')
    # ### end Alembic commands ###
    op.alter_column('subscription', 'custom_url', new_column_name='customUrl', existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100))
