#!/usr/bin/python3
"""Middleware between Flask and Apache

Originally Named Tubee.wsgi, place at root
"""
import sys
import logging
from Tubee import app as application
logging.basicConfig(stream=sys.stderr)
sys.path.insert(0, "/var/www/")
