"""empty message

Revision ID: 0749207b97a6
Revises: 4a60cbccd620
Create Date: 2019-11-21 21:28:15.292318

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0749207b97a6'
down_revision = '4a60cbccd620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    service_type = sa.Enum('ALL', 'PUSHOVER', 'LINE_NOTIFY', name='service')
    service_type.create(op.get_bind())
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service', service_type, nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=2000),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=2000),
               nullable=False)
        batch_op.drop_column('service')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), autoincrement=False, nullable=False),
    sa.Column('next_run_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('job_state', sa.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='apscheduler_jobs_pkey')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
