"""empty message

Revision ID: 27eb46e7065c
Revises: 9e026a59e418
Create Date: 2019-05-27 00:32:26.570589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27eb46e7065c'
down_revision = '9e026a59e418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('NOTIFICATION', 'PLAYLIST', 'DOWNLOAD', name='actionenum'), nullable=False),
    sa.Column('details', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_action'))
    )
    op.create_table('video',
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.String(length=30), nullable=True),
    sa.Column('uploaded_datetime', sa.DateTime(), nullable=True),
    sa.Column('thumbnails_url', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel.channel_id'], name=op.f('fk_video_channel_id_channel')),
    sa.PrimaryKeyConstraint('video_id', name=op.f('pk_video'))
    )
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expire_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('hub_infos', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('latest_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel', schema=None) as batch_op:
        batch_op.drop_column('latest_status')
        batch_op.drop_column('hub_infos')
        batch_op.drop_column('expire_datetime')
        batch_op.drop_column('description')

    op.drop_table('video')
    op.drop_table('action')
    # ### end Alembic commands ###
