"""empty message

Revision ID: 3b6601a39984
Revises: ce11b25c0bea
Create Date: 2019-05-16 22:42:40.905898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b6601a39984'
down_revision = 'ce11b25c0bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.alter_column('subscribe_datetime',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.alter_column('subscribe_datetime',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###
