"""empty message

Revision ID: 3b7a313a1cb3
Revises: e3d16f323b6a
Create Date: 2019-04-10 16:17:15.869479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7a313a1cb3'
down_revision = 'e3d16f323b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('country', sa.String(length=5), nullable=True))
    op.add_column('subscription', sa.Column('customUrl', sa.String(length=100), nullable=True))
    op.add_column('subscription', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'language')
    op.drop_column('subscription', 'customUrl')
    op.drop_column('subscription', 'country')
    # ### end Alembic commands ###
