"""Action username foreign key

Revision ID: 3e61825e9188
Revises: 8271190eec99
Create Date: 2021-01-28 03:12:12.355166

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3e61825e9188"
down_revision = "8271190eec99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_action_username_user"), "user", ["username"], ["username"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_action_username_user"), type_="foreignkey"
        )

    # ### end Alembic commands ###
