"""empty message

Revision ID: 4a841a1a3354
Revises: e54908090f3e
Create Date: 2019-04-09 13:02:46.589811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a841a1a3354'
down_revision = 'e54908090f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'host')
    op.drop_column('request', 'scheme')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('scheme', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=5), nullable=False))
    op.add_column('request', sa.Column('host', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False))
    # ### end Alembic commands ###
