"""empty message

Revision ID: 75b38284c03f
Revises: 61889220ba8f
Create Date: 2019-05-15 15:30:20.549544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75b38284c03f'
down_revision = '61889220ba8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), server_default='0', nullable=True))
    op.drop_column('user', 'master')
    op.add_column('user-subscription', sa.Column('subscribe_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('user-subscription', sa.Column('unsubscribe_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-subscription', 'unsubscribe_datetime')
    op.drop_column('user-subscription', 'subscribe_datetime')
    op.add_column('user', sa.Column('master', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
