"""empty message

Revision ID: 76df6ab4150a
Revises: a1502f920f26
Create Date: 2019-05-16 17:54:18.929326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '76df6ab4150a'
down_revision = 'a1502f920f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callback', schema=None) as batch_op:
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('arguments',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('received_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('kwargs',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('sent_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('arguments',
               existing_type=sqlite.JSON(),
               nullable=True)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('received_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('channel_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('renew_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('subscribe_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.alter_column('subscribe_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('renew_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('channel_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('received_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('method',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('arguments',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('sent_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('kwargs',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('callback', schema=None) as batch_op:
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('received_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('details',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('data',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('arguments',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('action',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)

    # ### end Alembic commands ###
