"""empty message

Revision ID: 88fff34fba54
Revises: c79111fd3943
Create Date: 2019-04-09 15:53:50.692543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88fff34fba54'
down_revision = 'c79111fd3943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'responded_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('responded_status', mysql.INTEGER(display_width=5), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
