"""empty message

Revision ID: 9497b16da8bc
Revises: c9e504f25783
Create Date: 2019-05-15 23:13:19.295909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9497b16da8bc'
down_revision = 'c9e504f25783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), autoincrement=True, nullable=True))
        batch_op.add_column(sa.Column('subscribe_datetime', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=False))
        batch_op.add_column(sa.Column('unsubscribe_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.drop_column('unsubscribe_datetime')
        batch_op.drop_column('subscribe_datetime')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
