"""empty message

Revision ID: a9a093c73a90
Revises: ec78836de0d5
Create Date: 2019-05-07 22:55:11.937496

"""
from alembic import op
import sqlalchemy as sa
# from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a9a093c73a90'
down_revision = 'ec78836de0d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('response',
               # existing_type=sqlite.JSON(),
               existing_type=sa.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('response',
               # existing_type=sqlite.JSON(),
               existing_type=sa.JSON(),
               nullable=False)

    # ### end Alembic commands ###
