"""empty message

Revision ID: b1108607b5b5
Revises: 
Create Date: 2019-05-17 12:43:11.774449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1108607b5b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('received_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('channel_id', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=True),
    sa.Column('details', sa.String(length=20), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callback'))
    )
    op.create_table('request',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('received_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    op.create_table('subscription',
    sa.Column('channel_id', sa.String(length=30), nullable=False),
    sa.Column('channel_name', sa.String(length=100), nullable=True),
    sa.Column('thumbnails_url', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.Column('custom_url', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('renew_datetime', sa.DateTime(), nullable=True),
    sa.Column('subscribe_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('unsubscribe_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id', name=op.f('pk_subscription'))
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('admin', sa.Boolean(), server_default='0', nullable=True),
    sa.Column('pushover_key', sa.String(length=40), nullable=True),
    sa.Column('youtube_credentials', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('username', name=op.f('pk_user'))
    )
    op.create_table('notification',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('initiator', sa.String(length=15), nullable=False),
    sa.Column('user_id', sa.String(length=30), nullable=True),
    sa.Column('sent_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('message', sa.String(length=2000), nullable=False),
    sa.Column('kwargs', sa.JSON(), nullable=True),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.username'], name=op.f('fk_notification_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_table('user-subscription',
    sa.Column('subscriber_username', sa.String(length=30), nullable=False),
    sa.Column('subscribing_channel_id', sa.String(length=30), nullable=False),
    sa.Column('subscribe_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('unsubscribe_datetime', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['subscriber_username'], ['user.username'], name=op.f('fk_user-subscription_subscriber_username_user')),
    sa.ForeignKeyConstraint(['subscribing_channel_id'], ['subscription.channel_id'], name=op.f('fk_user-subscription_subscribing_channel_id_subscription')),
    sa.PrimaryKeyConstraint('subscriber_username', 'subscribing_channel_id', name=op.f('pk_user-subscription'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-subscription')
    op.drop_table('notification')
    op.drop_table('user')
    op.drop_table('subscription')
    op.drop_table('request')
    op.drop_table('callback')
    # ### end Alembic commands ###
