"""empty message

Revision ID: c38453659a16
Revises: b1108607b5b5
Create Date: 2019-05-17 18:11:25.924882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38453659a16'
down_revision = 'b1108607b5b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('method', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callback', schema=None) as batch_op:
        batch_op.drop_column('path')
        batch_op.drop_column('method')

    # ### end Alembic commands ###
