"""empty message

Revision ID: c69d15999683
Revises: 8a3d9c34c719
Create Date: 2019-11-25 21:05:23.797286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c69d15999683'
down_revision = '8a3d9c34c719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('subscription',
    # sa.Column('subscriber_username', sa.String(length=30), nullable=False),
    # sa.Column('subscribing_channel_id', sa.String(length=30), nullable=False),
    # sa.Column('subscribe_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    # sa.Column('unsubscribe_datetime', sa.DateTime(), nullable=True),
    # sa.Column('tags', sa.PickleType(), nullable=True),
    # sa.ForeignKeyConstraint(['subscriber_username'], ['user.username'], name=op.f('fk_subscription_subscriber_username_user')),
    # sa.ForeignKeyConstraint(['subscribing_channel_id'], ['channel.channel_id'], name=op.f('fk_subscription_subscribing_channel_id_channel')),
    # sa.PrimaryKeyConstraint('subscriber_username', 'subscribing_channel_id', name=op.f('pk_subscription'))
    # )
    # op.drop_table('user-subscription')
    op.rename_table("user-subscription", "subscription")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('user-subscription',
    # sa.Column('subscriber_username', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    # sa.Column('subscribing_channel_id', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    # sa.Column('subscribe_datetime', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    # sa.Column('unsubscribe_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.Column('tags', postgresql.BYTEA(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['subscriber_username'], ['user.username'], name='fk_user-subscription_subscriber_username_user'),
    # sa.ForeignKeyConstraint(['subscribing_channel_id'], ['channel.channel_id'], name='fk_user-subscription_subscribing_channel_id_channel'),
    # sa.PrimaryKeyConstraint('subscriber_username', 'subscribing_channel_id', name='pk_user-subscription')
    # )
    # op.drop_table('subscription')
    op.rename_table("subscription", "user-subscription")
    # ### end Alembic commands ###
