"""empty message

Revision ID: c79111fd3943
Revises: 4a841a1a3354
Create Date: 2019-04-09 14:18:27.773154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79111fd3943'
down_revision = '4a841a1a3354'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-subscription', sa.Column('tags', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-subscription', 'tags')
    # ### end Alembic commands ###
