"""empty message

Revision ID: c960e1668521
Revises: 77c3afc76fc0
Create Date: 2019-12-01 23:48:37.783048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c960e1668521'
down_revision = '77c3afc76fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_id', type_=sa.String(length=36))
        batch_op.add_column(sa.Column('action_name', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('subscription_channel_id', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('subscription_username', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_action_subscription_username_subscription'), 'subscription', ['subscription_username', 'subscription_channel_id'], ['subscriber_username', 'subscribing_channel_id'])

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.JSON(), nullable=True))
        batch_op.alter_column('channel_id',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('thumbnails_url')
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('thumbnails_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('channel_id',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.drop_column('details')

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_id', type_=sa.Integer)
        batch_op.drop_constraint(batch_op.f('fk_action_subscription_username_subscription'), type_='foreignkey')
        batch_op.drop_column('subscription_username')
        batch_op.drop_column('subscription_channel_id')
        batch_op.drop_column('action_name')

    # ### end Alembic commands ###
