"""empty message

Revision ID: ce11b25c0bea
Revises: f74f13a006bb
Create Date: 2019-05-16 18:16:19.446443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce11b25c0bea'
down_revision = 'f74f13a006bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_notification_user_id_user'), 'user', ['user_id'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_notification_user_id_user'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
