"""empty message

Revision ID: d714b6c649f2
Revises: 27eb46e7065c
Create Date: 2019-05-27 17:38:30.045881

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd714b6c649f2'
down_revision = '27eb46e7065c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        # batch_op.drop_column('password')
        batch_op.alter_column('password', new_column_name='password_hash', type_=sa.String(length=128))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=70), nullable=False))
        # batch_op.drop_column('password_hash')
        batch_op.alter_column('password_hash', new_column_name='password', type_=sa.String(length=70))


    # ### end Alembic commands ###
