"""empty message

Revision ID: e3d16f323b6a
Revises: 88fff34fba54
Create Date: 2019-04-10 14:28:54.035605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d16f323b6a'
down_revision = '88fff34fba54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('thumbnails_url', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'thumbnails_url')
    # ### end Alembic commands ###
