"""empty message

Revision ID: e54908090f3e
Revises: 
Create Date: 2019-04-09 07:41:47.261913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54908090f3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user-subscription',
    sa.Column('subscriber_username', sa.String(length=30), nullable=False),
    sa.Column('subscribing_channel_id', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_username'], ['user.username'], ),
    sa.ForeignKeyConstraint(['subscribing_channel_id'], ['subscription.channel_id'], ),
    sa.PrimaryKeyConstraint('subscriber_username', 'subscribing_channel_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user-subscription')
    # ### end Alembic commands ###
