"""empty message

Revision ID: f74f13a006bb
Revises: 76df6ab4150a
Create Date: 2019-05-16 18:14:08.913603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f74f13a006bb'
down_revision = '76df6ab4150a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notification_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.VARCHAR(length=30), nullable=True))
        batch_op.create_foreign_key('fk_notification_user_id_user', 'user', ['user_id'], ['username'])

    # ### end Alembic commands ###
