"""empty message

Revision ID: 36a02dfb6a68
Revises: dd07ec8faec0
Create Date: 2019-06-15 08:50:53.562189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a02dfb6a68'
down_revision = 'dd07ec8faec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dropbox_credentials', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('dropbox_credentials')

    # ### end Alembic commands ###
