"""empty message

Revision ID: 9e026a59e418
Revises: c38453659a16
Create Date: 2019-05-17 19:29:56.192472

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e026a59e418'
down_revision = 'c38453659a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user-subscription_subscribing_channel_id_subscription', type_='foreignkey')
        op.rename_table('subscription', 'channel')
        batch_op.create_foreign_key(batch_op.f('fk_user-subscription_subscribing_channel_id_channel'), 'channel', ['subscribing_channel_id'], ['channel_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user-subscription', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_user-subscription_subscribing_channel_id_channel'), type_='foreignkey')
        op.rename_table('channel', 'subscription')
        batch_op.create_foreign_key('fk_user-subscription_subscribing_channel_id_subscription', 'subscription', ['subscribing_channel_id'], ['channel_id'])
    op.create_table('request',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('received_datetime', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('path', sa.String(length=100), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
