name: Docs (Docker Hub)

on:
  push:
    paths:
      - "README.md"
    branches:
      - "main"

jobs:
  update-docker-hub-readme:
    name: Update Docker Hub README
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update repository description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
