name: License Scan (FOSSA)

on:
  push:
    paths:
      - "pyproject.toml"
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Export requirements.txt
        run: |
          poetry export --dev -f requirements.txt --output requirements.txt

      # FOSSA's API Key are meant to be exposed as to doc
      - name: Scan license
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 2d7865a44aa575d857521faaee1a57f8
