name: Test, Build, Deploy

on:
  push:
    branches:
      - main
    paths:
      - "tubee/**"
      - "app.py"
      - "celery_worker.py"
      - "pyproject.toml"
      - "poetry.lock"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Testing
        run: |
          flask test --coverage

      - name: Report coverage
        uses: codecov/codecov-action@v1

  style:
    name: Lint Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Linting
        run: |
          flake8 tubee

  license:
    name: License Scan
    runs-on: ubuntu-latest
    if: ${{ github.event_path == 'pyproject.toml' || github.event_path == 'poetry.lock' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi

      - name: Export requirements.txt
        run: |
          poetry export --dev -f requirements.txt --output requirements.txt

      # FOSSA's API Key are meant to be exposed as to doc
      - name: Scan License
        uses: fossa-contrib/fossa-action@v1
        with:
          fossa-api-key: 2d7865a44aa575d857521faaee1a57f8

  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    needs: [test, style, license]
    if: |
      always() && (github.event_name != 'pull_request') &&
      (needs.test.result == 'success') && (needs.style.result == 'success') &&
      (needs.license.result == 'success' || needs.license.result == 'skipped')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ github.repository_owner }}/tubee
            ghcr.io/${{ github.repository_owner }}/tubee
          tags: |
            type=edge

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deployment:
    name: Deploy to Beta
    runs-on: ubuntu-latest
    environment: Beta
    needs: build
    if: ${{ always() && (github.event_name != 'pull_request') }}
    steps:
      - name: SSH and execute deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            docker pull tomy0000000/tubee:edge
            docker-compose up --detach
            docker network connect nginx_default tubee_app_beta
